server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/li525917388/configCloud/
          searchPaths: wfwConfig
          username: ldh
          password:
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
